
oac_group_names = {
    "1A": "Farming Communities",
    "1B": "Rural Tenants",
    "1C": "Ageing Rural Dwellers",
    "2A": "Students Around Campus",
    "2B": "Inner-City Students",
    "2C": "Comfortable Cosmopolitans",
    "2D": "Aspiring and Affluent",
    "3A": "Ethnic Family Life",
    "3B": "Endeavouring Ethnic Mix",
    "3C": "Ethnic Dynamics",
    "3D": "Aspirational Techies",
    "4A": "Rented Family Living",
    "4B": "Challenged Asian Terraces",
    "4C": "Asian Traits",
    "5A": "Urban Professionals and Families",
    "5B": "Ageing Urban Living",
    "6A": "Suburban Achievers",
    "6B": "Semi-Detached Suburbia",
    "7A": "Challenged Diversity",
    "7B": "Constrained Flat Dwellers",
    "7C": "White Communities",
    "7D": "Ageing City Dwellers",
    "8A": "Industrious Communities",
    "8B": "Challenged Terraced Workers",
    "8C": "Hard-Pressed Ageing Workers",
    "8D": "Migration and Churn"
}

oac_subgroup_names = {
    "1A1": "Rural workers and families",
    "1A2": "Established farming communities",
    "1A3": "Agricultural communities",
    "1A4": "Older farming communities",
    "1B1": "Rural Life",
    "1B2": "Rural white-collar workers",
    "1B3": "Ageing rural flat tenants",
    "1C1": "Rural employment and retirees",
    "1C2": "Renting rural retirement",
    "1C3": "Detached rural retirement",
    "2A1": "Student communal living",
    "2A2": "Student digs",
    "2A3": "Students and professionals",
    "2A4": "Inner city students",
    "2B1": "Students and commuters",
    "2B2": "Multicultural student neighbourhoods",
    "2C1": "Migrant families",
    "2C2": "Migrant commuters",
    "2C3": "Professional service cosmopolitans",
    "2D1": "Urban cultural mix",
    "2D2": "Highly-qualified quaternary workers",
    "2D3": "EU white-collar workers",
    "3A1": "Established renting families",
    "3A2": "Young families and students",
    "3B1": "Striving service workers",
    "3B2": "Bangladeshi mixed employment",
    "3B3": "Multi-ethnic professional service workers",
    "3C1": "Constrained neighbourhoods",
    "3C2": "Constrained commuters",
    "3D1": "New EU tech workers",
    "3D2": "Established tech workers",
    "3D3": "Old EU tech workers",
    "4A1": "Social renting young families",
    "4A2": "Private renting new arrivals",
    "4A3": "Commuters with young families",
    "4B1": "Asian terraces and flats",
    "4B2": "Pakistani communities",
    "4C1": "Achieving minorities",
    "4C2": "Multicultural new arrivals",
    "4C3": "Inner city ethnic mix",
    "5A1": "White professionals",
    "5A2": "Multi-ethnic professionals with families",
    "5A3": "Families in terraces and flats",
    "5B1": "Delayed retirement",
    "5B2": "Communal retirement",
    "5B3": "Self-sufficient retirement",
    "6A1": "Indian tech achievers",
    "6A2": "Comfortable suburbia",
    "6A3": "Detached retirement living",
    "6A4": "Ageing in suburbia",
    "6B1": "Multi-ethnic suburbia",
    "6B2": "White suburban communities",
    "6B3": "Semi-detached ageing",
    "6B4": "Older workers and retirement",
    "7A1": "Transitional Eastern European neighbourhoods",
    "7A2": "Hampered aspiration",
    "7A3": "Multi-ethnic hardship",
    "7B1": "Eastern European communities",
    "7B2": "Deprived neighbourhoods",
    "7B3": "Endeavouring flat dwellers",
    "7C1": "Challenged transitionaries",
    "7C2": "Constrained young families",
    "7C3": "Outer city hardship",
    "7D1": "Retired independent city dwellers",
    "7D2": "Retired communal city dwellers",
    "7D3": "Retired city hardship",
    "8A1": "Industrious transitions",
    "8A2": "Industrious hardship",
    "8B1": "Deprived blue-collar terraces",
    "8B2": "Hard pressed rented terraces",
    "8C1": "Ageing industrious workers",
    "8C2": "Ageing rural industry workers",
    "8C3": "Renting hard-pressed workers",
    "8D1": "Young hard-pressed families",
    "8D2": "Hard-pressed ethnic mix",
    "8D3": "Hard-Pressed European Settlers"
}
